version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-colorcounting
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=citizix
#      - MONGO_INITDB_ROOT_PASSWORD=S3cret