spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: color-messages
    listener:
      type: batch
  mvc:
    pathmatch:
      :matching-strategy: ant_path_matcher
  mongodb:
    embedded:
      version: 4.0.21
  redis:
    host: localhost
    port: 6379

test:
  topic: color-messages-test-topic



monitor:
  kafka:
    bootstrap:
      config: "PLAINTEXT://localhost:9085"

#spring.mvc.pathmatch.matching-strategy=ant_path_matcher